#!/bin/bash
#
# Copyright (C) 2011, 2014, 2019, 2020, 2021 Markus Kollmar
#
# This file is part of ESCAD.
#
# ESCAD is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ESCAD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with ESCAD.  If not, see <http://www.gnu.org/licenses/>.
##############################################################################

#### CONFIG:
ESCAD_ROOT_DIR="./"
ESCAD='package.lisp'
ESCAD_REST_SERVER='rest-server.js'
ESCAD_INIT_FILE="${ESCAD_ROOT_DIR}escad_init.lisp"
ESCAD_LOGFILE="${ESCAD_ROOT_DIR}escad.log"
ESCAD_ERROR_LOGFILE="${ESCAD_ROOT_DIR}escad_error.log"
#LISP_BIN="$(which clisp)" # clisp
#LISP_BIN_PRELOAD="$(which clisp) -i ${ESCAD_ROOT_DIR}${ESCAD}" # clisp
#LISP_BIN_LOAD="$(which clisp) ${ESCAD_ROOT_DIR}${ESCAD}" # clisp
LISP_BIN="$(which sbcl)" # sbcl
LISP_BIN_PRELOAD="$(which sbcl) --load ${ESCAD_ROOT_DIR}${ESCAD}" # sbcl
#LISP_BIN_PRELOAD="$(which sbcl) --eval '(setf sb-impl::*default-external-format* :UTF-8)' --load ${ESCAD_ROOT_DIR}${ESCAD}" # sbcl
LISP_BIN_LOAD="$(which sbcl) --load ${ESCAD_ROOT_DIR}${ESCAD}" # sbcl
DOT_BIN=$(which dot)
LATEX_BIN=$(which pdflatex)
MODE='terminal' # default mode
#### END CONFIG

print_status() {
    ESCAD_PS=$(ps hax)
    ESCAD_TEST=$(echo ${ESCAD_PS} | grep "${ESCAD}")
    if [[ "${ESCAD_TEST}" != "" ]]
    then
	echo "ESCAD is running!"
    else
	echo "No ESCAD is running!"
    fi
}

print_usage() {
    echo "Usage: $0 [start [terminal | emacs | gui-tk | net-lisp | net-rest] | status |stop]"
    echo "<Terminal> is the default mode since it has little requirements. However <emacs> is currently recommended as good supported user-interface."
}


start_configuration() {
case "$MODE" in
  'terminal')  # default
        ${LISP_BIN_PRELOAD}
	;;
  'emacs')
	echo "Starting emacs client..."
	emacs --load ./ui/escad-mode.el --eval "(escad-make-layout)"
	;;
  'gui-tk')
	echo "Starting Tk gui client..."
	${LISP_BIN_LOAD} gui-tk # TODO!
	;;
  'net-lisp')
      echo "Starting escad accepting common lisp over network socket (e.g. with telnet)..."
      ${LISP_BIN_LOAD} net-lisp
      ## alternativ:
      #rm -f escad_fifo; mkfifo escad_fifo
      #cat escad_fifo | ${LISP_BIN_PRELOAD} | nc -k -l 3000 > escad_fifo
      ;;
  'net-rest')
      echo "Starting escad accepting REST (via nodejs) based http network-connection (e.g. with web-browser)..."
      ${LISP_BIN_LOAD} net-lisp >${ESCAD_LOGFILE} 2>${ESCAD_ERROR_LOGFILE} &
      #rm -f escad_fifo; mkfifo escad_fifo
      #cat escad_fifo | ${LISP_BIN_PRELOAD} | nc -k -l 3000 > escad_fifo 2>${ESCAD_ERROR_LOGFILE}
	sleep 2
	node ${ESCAD_REST_SERVER}
	;;
    *)
	echo "ERROR: unknown mode <${MODE}>!"
	print_usage
	;;
esac
}

stop_configuration() {
    killall node
    kill $(ps aux | grep -e ${ESCAD} | grep -v grep | awk '{print $2}')
    rm -f escad_fifo
}

# Make prerequsite test and setting:
test_environment() {
    if [[ -z ${LISP_BIN} ]]
	then
	echo "ERROR: No supported common-lisp implementation (clisp/sbcl) available!"
	exit
    fi
    if [[ -z ${DOT_BIN} ]]
	then
	echo "WARNING: Export to dot may not work! (missing ${DOT_BIN})"
    fi
    if [[ -z ${LATEX_BIN} ]]
        then
	echo "WARNING: Export to PDF may not work! (missing ${LATEX_BIN})"
    fi
    test -r ~/.escad && ${ESCAD_DEFAULT_USER_INIT_FILE}="~/.escad"
}


## MAIN
test "${2}" != "" && MODE=$2

case "$1" in
  'start')
        # Load escad as in clisp:
	test_environment
	start_configuration
	;;
  'status')
	print_status
	;;
  'stop')
	stop_configuration
	;;
    *)
	print_usage
	;;
esac

exit 0
